Repository chakra-core/ChakraCore, pull requests merged in 2018-03, with the labels that each got.

#4743 Remove Intl.cpp/Intl.h from PlatformAgnostic
  bin/ch/WScriptJsrt.cpp
  lib/Common/CommonDefines.h
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  lib/Runtime/PlatformAgnostic/Chakra.Runtime.PlatformAgnostic.vcxproj
  lib/Runtime/PlatformAgnostic/ICU.h
  lib/Runtime/PlatformAgnostic/IPlatformAgnosticResource.h
  lib/Runtime/PlatformAgnostic/Intl.h
  lib/Runtime/PlatformAgnostic/Platform/CMakeLists.txt
  lib/Runtime/PlatformAgnostic/Platform/Common/Intl.cpp
  test/rlexedirs.xml
Labels: Intl-ICU

#4766 Allow ChakraFull to build with Windows Kit ICU
  Build/Chakra.Build.props
  bin/ChakraCore/ChakraCore.vcxproj
  bin/ch/CMakeLists.txt
  bin/ch/WScriptJsrt.cpp
  bin/ch/ch.vcxproj
  bin/ch/stdafx.h
  lib/Common/CommonDefines.h
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  lib/Runtime/PlatformAgnostic/Chakra.Runtime.PlatformAgnostic.vcxproj
  lib/Runtime/PlatformAgnostic/Chakra.Runtime.PlatformAgnostic.vcxproj.filters
  lib/Runtime/PlatformAgnostic/ChakraICU.h
  lib/Runtime/PlatformAgnostic/Platform/Common/UnicodeText.ICU.cpp
  lib/Runtime/PlatformAgnostic/UnicodeText.h
Labels: Intl-ICU

#4794 Clean up WScript.Platform usage, introduce new exclude_windows tag
  test/Array/array_qsortr.js
  test/Array/rlexe.xml
  test/AsmJs/MathBuiltinsCall.js
  test/Date/DateCtr.js
  test/Date/formatting_xplat.js
  test/Date/rlexe.xml
  test/Date/xplatInterval.js
  test/Error/stack.js
  test/JSON/replacerFunction.js
  test/es6/ES6TypedArrayExtensions.js
  test/runtests.cmd
  test/runtests.py
Labels: Dev Experience

#4806 Implement JsGetProxyProperties API fixes #950
  bin/ChakraCore/ChakraCore.def
  bin/ch/ChakraRtInterface.cpp
  bin/ch/ChakraRtInterface.h
  bin/ch/WScriptJsrt.cpp
  bin/ch/WScriptJsrt.h
  lib/Jsrt/ChakraCore.h
  lib/Jsrt/Jsrt.cpp
  lib/Runtime/Library/JavascriptProxy.cpp
  lib/Runtime/Library/JavascriptProxy.h
  test/es6/ProxyPropertiesAPI.js
  test/es6/rlexe.xml
Labels: External Contributor

#4777 Add ccache option to CMakeLists.txt and build.sh
  CMakeLists.txt
  build.sh
Labels: External Contributor

#4815 Add default version of ICU to download helper
  tools/configure_icu.py
Labels: Dev Experience, Intl-ICU

#4615 Date.UTC should return NaN for out-of-range time value
  lib/Runtime/Library/DateImplementation.cpp
  test/Date/dateutc.baseline
  test/Date/dateutc.js
Labels: External Contributor

#4802 OS#16291886 (OSS-Fuzz #6657) Handle uloc_forLanguageTag failing to parse the entire input while still returning U_ZERO_ERROR
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  test/Intl/common.js
  test/Intl/rlexe.xml
Labels: Intl-ICU

#4847 Asm.js nullptr read on fround check
  lib/Runtime/Language/AsmJsModule.cpp
  test/AsmJs/bug16253406.js
  test/AsmJs/rlexe.xml
Labels: Bug

#4867 IsIn FastPath with string as src1
  lib/Backend/Lower.cpp
Labels: Bug

#1300 [Updated] #110 Convert rlexe.xml tags to use new build architecture and type terms
  test/Array/rlexe.xml
  test/AsmJs/rlexe.xml
  test/Closures/rlexe.xml
  test/DynamicCode/rlexe.xml
  test/Function/rlexe.xml
  test/GlobalFunctions/rlexe.xml
  test/JSON/rlexe.xml
  test/Lib/rlexe.xml
  test/Miscellaneous/rlexe.xml
  test/Object/rlexe.xml
  test/Optimizer/rlexe.xml
  test/Regex/rlexe.xml
  test/TaggedIntegers/rlexe.xml
  test/UnifiedRegex/rlexe.xml
  test/bailout/rlexe.xml
  test/es5/rlexe.xml
  test/es6/rlexe.xml
  test/runtests.cmd
  test/runtests.py
  test/stackfunc/rlexe.xml
  test/strict/rlexe.xml
  test/typedarray/rlexe.xml
Labels: Committed, External Contributor, Waiting

#4886 OS#16605917 [OSS-Fuzz #7060] - Reset status when we fail to set the gregorian change on a calendar
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  test/Intl/DateTimeFormat.js
Labels: Intl-ICU
