Repository chakra-core/ChakraCore, pull requests merged in 2018-05, with the labels that each got.

#5029 Update NativeTests.exe to use TestHooks, add UnicodeText tests from #4905
  bin/ChakraCore/TestHooks.cpp
  bin/ChakraCore/TestHooks.h
  bin/NativeTests/FunctionExecutionTest.h
  bin/NativeTests/NativeTests.cpp
  bin/NativeTests/NativeTests.def
  bin/NativeTests/NativeTests.vcxproj
  bin/NativeTests/UnicodeTextTests.cpp
  bin/NativeTests/stdafx.h
Labels: Codebase Quality, Dev Experience

#5075 OS#17172584: Add handling of more OOM scenarios in ICU
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
Labels: Intl-ICU

#5036 Restore SuperRestrictionState after methods fix #5030
  lib/Parser/Parse.cpp
  test/es6/classes.js
Labels: External Contributor

#5129 enable wasm non-trapping float to int conversions
  lib/Common/ConfigFlagsList.h
  lib/WasmReader/WasmParseTree.cpp
Labels: WebAssembly

#5136 Enable Wasm SignExtend operators by default
  lib/Common/ConfigFlagsList.h
  lib/WasmReader/WasmBinaryOpCodes.h
  lib/WasmReader/WasmParseTree.cpp
  lib/WasmReader/WasmParseTree.h
Labels: WebAssembly

#5174 OS#17513493 (OSS-Fuzz 7950): add workaround for redefined option getters
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  test/Intl/common.js
Labels: Intl-ICU

#5220 typeof on detached ArrayBuffer consistent behavior
  lib/Runtime/Language/JavascriptOperators.cpp
  lib/Runtime/Library/TypedArray.cpp
  test/typedarray/rlexe.xml
  test/typedarray/typeofDetached.js
Labels: Bug

#5242 Remove _ABSTRACT
  lib/Common/CommonPal.h
  lib/Common/DataStructures/BaseDictionary.h
  lib/Runtime/Base/ThreadContext.cpp
  lib/Runtime/Base/ThreadContext.h
  lib/Runtime/Base/ThreadServiceWrapper.h
  lib/Runtime/Language/InlineCache.h
  lib/Runtime/Library/ArgumentsObject.h
  lib/Runtime/Library/ConcatString.h
  lib/Runtime/Library/JavascriptArrayIndexEnumeratorBase.h
  lib/Runtime/Library/JavascriptString.h
Labels: Codebase Quality

#5249 IRBuilder implicit operations before first statement boundary
  lib/Backend/IRBuilder.cpp
Labels: Bug
