Repository chakra-core/ChakraCore, pull requests merged in 2018-04, with the labels that each got.

#4910 Lower Var Untag
  lib/Backend/GlobOpt.cpp
  lib/Backend/GlobOptFields.cpp
  lib/Backend/IR.cpp
  lib/Backend/IRBuilder.cpp
  lib/Backend/Lower.cpp
  lib/Backend/LowerMDShared.cpp
  lib/Backend/Opnd.cpp
  lib/Backend/Sym.cpp
  lib/Backend/Sym.h
  lib/Backend/TempTracker.cpp
  lib/Backend/arm/LowerMD.cpp
  lib/Backend/arm64/LowerMD.cpp
Labels: Bug

#4994 Update RecyclerExecuteICUWithRetry to provide more verbose asserts
  lib/Runtime/Library/IntlEngineInterfaceExtensionObject.cpp
  lib/Runtime/PlatformAgnostic/ChakraICU.h
Labels: Intl-ICU

#4977 Fix clang compiler error caused by enum < 0
  pal/src/shmemory/shmemory.cpp
Labels: External Contributor

#5049 Add -only flag to UnitTestFramework to run subset of tests
  test/UnitTestFramework/UnitTestFramework.js
Labels: Dev Experience
