Repository chakra-core/ChakraCore, pull requests merged in 2018-06, with the labels that each got.

#5290 Fix potential buffer overread in CountNewlines in Scan.cpp
  lib/Parser/Scan.cpp
  lib/Parser/Scan.h
Labels: External Contributor

#5279 Implement -module flag in ch for running a script as a module
  bin/ch/HostConfigFlagsList.h
  bin/ch/WScriptJsrt.cpp
  bin/ch/WScriptJsrt.h
  bin/ch/ch.cpp
  test/es6module/multiple-roots-circular.js
  test/es6module/otherModule.js
  test/es6module/rlexe.xml
Labels: External Contributor

#5027 RegExp syntax error for invalid Unicode codepoint fix #2753
  lib/Parser/RegexParser.cpp
  test/es6/unicode_escape_sequences.baseline
  test/es6/unicode_escape_sequences.js
Labels: External Contributor

#5351 Asm.js: Bytecode generator stack space
  lib/Runtime/Language/AsmJsByteCodeGenerator.cpp
  test/AsmJs/emit_recursive.js
  test/AsmJs/rlexe.xml
Labels: Bug

#5404 Jenkins: Fix daily builds of ARM by building on Windows 8.1 for now.
  netci.groovy
Labels: Continuous Integration
