Repository chakra-core/ChakraCore, pull requests merged in 2018-09, with the labels that each got.

#5659 Fix a couple of typos in Jsrt Header comments
  lib/Jsrt/ChakraCommon.h
  lib/Jsrt/ChakraCore.h
Labels: External Contributor

#5658 Add check for non-ascii fix:#4268
  jenkins/check_ascii.sh
  jenkins/check_file_ascii.sh
  lib/Runtime/Library/JavascriptString.cpp
  netci.groovy
Labels: External Contributor

#5685 Remove questionable uses of LiteralString class
  lib/Runtime/Library/BoundFunction.cpp
  lib/Runtime/Library/CompoundString.h
  lib/Runtime/Library/JavascriptFunction.cpp
  lib/Runtime/Library/JavascriptLibrary.cpp
  lib/Runtime/Library/ScriptFunction.cpp
  lib/Runtime/Library/StringCacheList.h
Labels: Performance

#5684 inline JsBuiltIn helper CallInstanceFunction
  lib/Backend/Inline.cpp
  lib/Backend/Inline.h
  lib/Backend/InliningDecider.cpp
  lib/Common/ConfigFlagsList.h
  lib/Runtime/ByteCode/ByteCodeEmitter.cpp
  lib/Runtime/ByteCode/OpCodes.h
  lib/Runtime/Library/EngineInterfaceObject.cpp
  lib/Runtime/Library/EngineInterfaceObject.h
  lib/Runtime/Library/JavascriptBuiltInFunctionList.h
  lib/Runtime/Library/JavascriptBuiltInFunctions.cpp
  lib/Runtime/Library/JavascriptLibrary.cpp
  lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js
  lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.32b.h
  lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.bc.64b.h
  lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.nojit.bc.32b.h
  lib/Runtime/Library/JsBuiltIn/JsBuiltIn.js.nojit.bc.64b.h
  lib/Runtime/LibraryFunction.h
  test/DebuggerCommon/returnedvaluetests1.js
  test/DebuggerCommon/returnedvaluetests1.js.dbg.baseline
  test/inlining/InlineCallInstanceFunction.baseline
  test/inlining/InlineCallInstanceFunction.js
  test/inlining/rlexe.xml
Labels: Bytecode-Update, Performance

#5710 Do not skip FromPropertyDescriptor in Proxy DefineOwnProperty
  lib/Runtime/Language/JavascriptOperators.cpp
  lib/Runtime/Library/JavascriptProxy.cpp
  test/es6/proxybugs.js
Labels: External Contributor
