Repository chakra-core/ChakraCore, pull requests merged in 2019-02, with the labels that each got.

#5776 Uniformity in headers
  README.md
Labels: External Contributor

#5887 WebAssembly spec tests harness improvements
  test/WasmSpec/baselines/testsuite/js-api/global/constructor.any.baseline
  test/WasmSpec/baselines/testsuite/js-api/global/toString.any.baseline
  test/WasmSpec/baselines/testsuite/js-api/global/value-get-set.any.baseline
  test/WasmSpec/baselines/testsuite/js-api/global/valueOf.any.baseline
  test/WasmSpec/baselines/testsuite/js-api/interface.any.baseline
  test/WasmSpec/baselines/testsuite/js-api/table/assertions.baseline
  test/WasmSpec/convert-test-suite/config.json5
  test/WasmSpec/convert-test-suite/index.js
  test/WasmSpec/convert-test-suite/package-lock.json
  test/WasmSpec/convert-test-suite/package.json
  test/WasmSpec/jsapi.js
  test/WasmSpec/rlexe.xml
Labels: WebAssembly

#5889 WebAssembly fix tee_local behavior
  lib/WasmReader/WasmByteCodeGenerator.cpp
  test/WasmSpec/baselines/testsuite/core/br.baseline
  test/WasmSpec/baselines/testsuite/core/return.baseline
  test/WasmSpec/baselines/testsuite/core/unreachable.baseline
Labels: Bug, ES Spec Conformance, WebAssembly
